---
title: Error和错误处理
tags: [javascript]
date: 2015-09-02
excerpt: JavaScript中的内置对象Error
author: jizhi.w77@foxmail.com
comments: true
---

JavaScript中基本的错误处理对象Error，通过Error可以构造一个错误对象，当运行时错误产生时，Error的实例对象会被抛出。除了通用的Error构造函数外，JavaScript还有6个其他类型的错误构造函数：`EvalError`、`RangeError`、`ReferenceError`、`SyntaxError`、`TypeError`和`URIError`。

## 描述

当代码运行时的发生错误，会创建新的Error对象，并将其抛出。

## 示例

###  抛出一个基本错误

通常你会使用throw关键字来抛出你创建的Error对象。可以使用 try...catch 结构来处理异常:

```js
try {
    throw new Error("Whoops!");
} catch (e) {
    alert(e.name + ": " + e.message);
}
```

### 处理一个特定错误

可以通过判断异常的类型来特定处理某一类的异常,即判断 constructor 属性，当使用现代Javascript引擎时,可使用instanceof 关键字：

```js
try {
    foo.bar();
} catch (e) {
    if (e instanceof EvalError) {
        alert(e.name + ": " + e.message);
    } else if (e instanceof RangeError) {
        alert(e.name + ": " + e.message);
    }
    // ... etc
}
```

### 自定义异常类型

```js
// Create a new object, that prototypally inherits from the Error constructor.
function MyError(message) {
  this.name = 'MyError';
  this.message = message || 'Default Message';   this.stack = (new Error()).stack;
}
MyError.prototype = Object.create(Error.prototype);
MyError.prototype.constructor = MyError;

try {
  throw new MyError();
} catch (e) {
  console.log(e.name);     // 'MyError'
  console.log(e.message);  // 'Default Message'
}

try {
  throw new MyError('custom message');
} catch (e) {
  console.log(e.name);     // 'MyError'
  console.log(e.message);  // 'custom message'
}
```